blog/urls.py
from django.conf.urls import patterns, url
from . import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'microblog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r"^$", views.PostListView.as_view(), name="list"),
    url(r"^(?P<pk>\d+)/$", views.PostDetailView.as_view(), name="detail"),
)

microblog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from . import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'microblog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r"^$", views.HomePageView.as_view(), name="home"),
    url(r"^blog/", include("blog.urls", namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Post(models.Model):
	created_at = models.DateTimeField(auto_now_add=True, editable=False)
	updated_at = models.DateTimeField(auto_now=True, editable=False)
	title = models.CharField(max_length=255)
	slug = models.SlugField(max_length=255, blank=True, default='')
	content = models.TextField()
	published = models.BooleanField(default=True)
	author = models.ForeignKey(User, related_name="posts")

	class Meta:
		ordering = ["-created_at", "title"]

	def __unicode__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		super(Post, self).save(*args, **kwargs)
# Create your models here.

blog/views.py
from django.views.generic import ListView, DetailView
from .models import Post

class PublishPostsMixin(object):
	def get_queryset(self):
		queryset = super(PublishPostsMixin, self).get_queryset()
		return queryset.filter(published=True)


class PostListView(PublishPostsMixin, ListView):
	model = Post

class PostDetailView(PublishPostsMixin, DetailView):
	model = Post

microblog/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
	template_name = "index.html"

blog/templates/blog/post_list.html
{% extends "_layouts/base.html" %}

{% block page_title %}Blog posts | {% endblock %}

{% block page_content %}
<h2>Blog Posts</h2>
<ul>
    {% for post in post_list %}
    <li><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></li>
    {% empty %}
    <li>Sorry, no posts yet. Check back soon!</li>
    {% endfor %}
</ul>
{% endblock %}

blog/templates/post_detail.html
{% extends "_layouts/base.html" %}

{% block page_title %}{{post.title}} | {% endblock %}

{% block page_content %}
<h2>{{page.title}}</h2>
{{ post.content|linebreaks }}
<p>{{ post.updated_at }}</p>
<p><a href="{% url 'blog:list' %}">Return Home</a></p>
{% endblock %}

blog/templates/post_list.html
{% extends "_layouts/base.html" %}

{% block page_title %}Blog posts | {% endblock %}

{% block page_content %}
<h2>Blog Posts</h2>
<ul>
    {% for post in post_list %}
    <li><a href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a></li>
    {% empty %}
    <li>Sorry, no posts yet. Check back soon!</li>
    {% endfor %}
</ul>
{% endblock %}

microblog/templates/_layouts/base.html
<!doctype html>
<html>
    <head>
        <title>{% block page_title %}{% endblock %}Microblog</title>
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css">
    </head>
    <body>
    	<h1>Welcome to my site</h1>
        {% block page_content %}{% endblock %}
    </body>
</html>

microblog/templates/index.html
{% extends "_layouts/base.html" %}
{% block page_content %}
<a href="{% url 'blog:list' %}">Read my blog</a>
{% endblock %}